CREATE TABLE VehicleModel(
	Id INT PRIMARY KEY IDENTITY,
	MakeId INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Abrv NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE VehicleMake(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(50) NOT NULL,
	Abrv NVARCHAR(50) NOT NULL UNIQUE
);